name: Feature request
description: Suggest an improvement or new feature
title: "[Feature] "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Please keep it outcome-focused.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: "As a user, I want... so that..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like PRNudge to do?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches you’ve tried?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, screenshots, examples, constraints (compliance, repo size, workflow rules).
    validations:
      required: false
